export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      goals: {
        Row: {
          goal_id: string
          goal_name: string
          goal_description: string
          goal_type: string
          goal_horizon: string
          goal_timescale: string
          goal_scope: string
          goal_abstraction_level: string
          identity_relevance: number
          existential_weight: number
          goal_story: string
          success_definition: string
          progress_metric_name: string
          progress_current_value: number
          progress_target_value: number
          progress_unit: string
          progress_confidence: number
          progress_velocity: number
          progress_volatility: number
          milestones: Json
          milestone_completion_rate: number
          supporting_habits: string[]
          supporting_tasks: string[]
          conflicting_goals: string[]
          resource_requirements: string
          strategy_notes: string
          risk_factors: string
          risk_probability: number
          risk_impact: number
          mitigation_strategies: string
          fallback_goals: string
          tags: string[]
          labels: string[]
          confidence_level: number
          review_status: string
          review_notes: string
          notes: string
          created_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          goal_id?: string
          goal_name: string
          goal_description?: string
          goal_type?: string
          goal_horizon?: string
          goal_timescale?: string
          goal_scope?: string
          goal_abstraction_level?: string
          identity_relevance?: number
          existential_weight?: number
          goal_story?: string
          success_definition?: string
          progress_metric_name?: string
          progress_current_value?: number
          progress_target_value?: number
          progress_unit?: string
          progress_confidence?: number
          progress_velocity?: number
          progress_volatility?: number
          milestones?: Json
          milestone_completion_rate?: number
          supporting_habits?: string[]
          supporting_tasks?: string[]
          conflicting_goals?: string[]
          resource_requirements?: string
          strategy_notes?: string
          risk_factors?: string
          risk_probability?: number
          risk_impact?: number
          mitigation_strategies?: string
          fallback_goals?: string
          tags?: string[]
          labels?: string[]
          confidence_level?: number
          review_status?: string
          review_notes?: string
          notes?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          goal_id?: string
          goal_name?: string
          goal_description?: string
          goal_type?: string
          goal_horizon?: string
          goal_timescale?: string
          goal_scope?: string
          goal_abstraction_level?: string
          identity_relevance?: number
          existential_weight?: number
          goal_story?: string
          success_definition?: string
          progress_metric_name?: string
          progress_current_value?: number
          progress_target_value?: number
          progress_unit?: string
          progress_confidence?: number
          progress_velocity?: number
          progress_volatility?: number
          milestones?: Json
          milestone_completion_rate?: number
          supporting_habits?: string[]
          supporting_tasks?: string[]
          conflicting_goals?: string[]
          resource_requirements?: string
          strategy_notes?: string
          risk_factors?: string
          risk_probability?: number
          risk_impact?: number
          mitigation_strategies?: string
          fallback_goals?: string
          tags?: string[]
          labels?: string[]
          confidence_level?: number
          review_status?: string
          review_notes?: string
          notes?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
      }
      career_applications: {
        Row: {
          application_id: string
          company_name: string
          company_industry: string
          company_size: string
          role_title: string
          role_level: string
          role_type: string
          role_location: string
          remote_policy: string
          compensation_band: string
          currency: string
          application_date: string
          application_channel: string
          application_source: string
          referral_used: number
          resume_version_id: string
          cover_letter_version_id: string
          portfolio_version_id: string
          screening_completed: number
          interview_rounds_planned: number
          interview_rounds_completed: number
          offer_received: number
          offer_details: string
          decision_deadline: string | null
          decision_made: number
          rejection_received: number
          rejection_reason: string
          feedback_received: string
          lessons_learned: string
          emotional_impact: string
          career_alignment_score: number
          status: string
          created_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          application_id?: string
          company_name: string
          company_industry?: string
          company_size?: string
          role_title: string
          role_level?: string
          role_type?: string
          role_location?: string
          remote_policy?: string
          compensation_band?: string
          currency?: string
          application_date?: string
          application_channel?: string
          application_source?: string
          referral_used?: number
          resume_version_id?: string
          cover_letter_version_id?: string
          portfolio_version_id?: string
          screening_completed?: number
          interview_rounds_planned?: number
          interview_rounds_completed?: number
          offer_received?: number
          offer_details?: string
          decision_deadline?: string | null
          decision_made?: number
          rejection_received?: number
          rejection_reason?: string
          feedback_received?: string
          lessons_learned?: string
          emotional_impact?: string
          career_alignment_score?: number
          status?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          application_id?: string
          company_name?: string
          company_industry?: string
          company_size?: string
          role_title?: string
          role_level?: string
          role_type?: string
          role_location?: string
          remote_policy?: string
          compensation_band?: string
          currency?: string
          application_date?: string
          application_channel?: string
          application_source?: string
          referral_used?: number
          resume_version_id?: string
          cover_letter_version_id?: string
          portfolio_version_id?: string
          screening_completed?: number
          interview_rounds_planned?: number
          interview_rounds_completed?: number
          offer_received?: number
          offer_details?: string
          decision_deadline?: string | null
          decision_made?: number
          rejection_received?: number
          rejection_reason?: string
          feedback_received?: string
          lessons_learned?: string
          emotional_impact?: string
          career_alignment_score?: number
          status?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
      }
      attachments: {
        Row: {
          attachment_id: string
          file_name: string
          original_file_name: string
          file_extension: string
          mime_type: string
          file_size_bytes: number
          storage_backend: string
          storage_path: string
          encryption_algorithm: string
          encryption_key_id: string
          compression_used: number
          compression_ratio: number
          attached_entity_type: string
          attached_entity_id: string | null
          attachment_role: string
          embedding_supported: number
          is_embedded: number
          version_index: number
          version_parent_id: string | null
          checksum_sha256: string
          checksum_verified: number
          text_extracted: number
          ocr_performed: number
          preview_available: number
          attachment_notes: string
          created_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          attachment_id?: string
          file_name: string
          original_file_name?: string
          file_extension?: string
          mime_type?: string
          file_size_bytes?: number
          storage_backend?: string
          storage_path?: string
          encryption_algorithm?: string
          encryption_key_id?: string
          compression_used?: number
          compression_ratio?: number
          attached_entity_type?: string
          attached_entity_id?: string | null
          attachment_role?: string
          embedding_supported?: number
          is_embedded?: number
          version_index?: number
          version_parent_id?: string | null
          checksum_sha256?: string
          checksum_verified?: number
          text_extracted?: number
          ocr_performed?: number
          preview_available?: number
          attachment_notes?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          attachment_id?: string
          file_name?: string
          original_file_name?: string
          file_extension?: string
          mime_type?: string
          file_size_bytes?: number
          storage_backend?: string
          storage_path?: string
          encryption_algorithm?: string
          encryption_key_id?: string
          compression_used?: number
          compression_ratio?: number
          attached_entity_type?: string
          attached_entity_id?: string | null
          attachment_role?: string
          embedding_supported?: number
          is_embedded?: number
          version_index?: number
          version_parent_id?: string | null
          checksum_sha256?: string
          checksum_verified?: number
          text_extracted?: number
          ocr_performed?: number
          preview_available?: number
          attachment_notes?: string
          created_at?: string
          updated_at?: string
          user_id?: string
        }
      }
      analytics_events: {
        Row: {
          event_id: string
          event_type: string
          event_subtype: string
          event_timestamp: string
          related_entity_type: string
          related_entity_id: string | null
          metric_name: string
          metric_value: number
          metric_unit: string
          aggregation_window: string
          aggregation_method: string
          baseline_value: number
          delta_value: number
          trend_direction: string
          anomaly_detected: number
          anomaly_score: number
          confidence_interval: number
          analytics_notes: string
          created_at: string
          user_id: string
        }
        Insert: {
          event_id?: string
          event_type: string
          event_subtype?: string
          event_timestamp?: string
          related_entity_type?: string
          related_entity_id?: string | null
          metric_name?: string
          metric_value?: number
          metric_unit?: string
          aggregation_window?: string
          aggregation_method?: string
          baseline_value?: number
          delta_value?: number
          trend_direction?: string
          anomaly_detected?: number
          anomaly_score?: number
          confidence_interval?: number
          analytics_notes?: string
          created_at?: string
          user_id?: string
        }
        Update: {
          event_id?: string
          event_type?: string
          event_subtype?: string
          event_timestamp?: string
          related_entity_type?: string
          related_entity_id?: string | null
          metric_name?: string
          metric_value?: number
          metric_unit?: string
          aggregation_window?: string
          aggregation_method?: string
          baseline_value?: number
          delta_value?: number
          trend_direction?: string
          anomaly_detected?: number
          anomaly_score?: number
          confidence_interval?: number
          analytics_notes?: string
          created_at?: string
          user_id?: string
        }
      }
      user_settings: {
        Row: {
          settings_id: string
          user_id: string
          workspace_id: string
          tenant_id: string
          access_scope: string
          read_permission_level: string
          write_permission_level: string
          delete_permission_level: string
          share_permission_level: string
          inherit_permissions: number
          permission_notes: string
          review_cycle_type: string
          review_cycle_interval: string
          lifecycle_expected_next_state: string
          default_visibility: string
          default_tags: string[]
          archival_rules: Json
          audit_preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          settings_id?: string
          user_id?: string
          workspace_id?: string
          tenant_id?: string
          access_scope?: string
          read_permission_level?: string
          write_permission_level?: string
          delete_permission_level?: string
          share_permission_level?: string
          inherit_permissions?: number
          permission_notes?: string
          review_cycle_type?: string
          review_cycle_interval?: string
          lifecycle_expected_next_state?: string
          default_visibility?: string
          default_tags?: string[]
          archival_rules?: Json
          audit_preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          settings_id?: string
          user_id?: string
          workspace_id?: string
          tenant_id?: string
          access_scope?: string
          read_permission_level?: string
          write_permission_level?: string
          delete_permission_level?: string
          share_permission_level?: string
          inherit_permissions?: number
          permission_notes?: string
          review_cycle_type?: string
          review_cycle_interval?: string
          lifecycle_expected_next_state?: string
          default_visibility?: string
          default_tags?: string[]
          archival_rules?: Json
          audit_preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}
