use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct JobApplication {
    // 1. CORE IDENTITY & PIPELINE STATUS
    pub job_application_id: String,
    pub job_application_slug: String,
    pub job_title: String,
    pub job_title_normalized: Option<String>,
    pub job_level: Option<String>, // junior, mid, senior, staff, lead
    pub job_employment_type: Option<String>, // full_time, part_time, contract, internship
    pub job_work_mode: Option<String>, // onsite, hybrid, remote
    pub job_department: Option<String>,
    pub job_function: Option<String>,
    pub job_industry: Option<String>,
    pub job_domain: Option<String>,
    pub job_priority_level: i32,
    pub job_interest_level: i32,
    pub job_fit_score: f64,
    pub job_visibility: String, // active, archived
    pub job_status: String,     // draft, applied, interviewing, offer, rejected, ghosted, withdrawn
    pub job_stage: Option<String>,
    pub job_stage_order: i32,
    pub job_version: i32,

    // 2. COMPANY PROFILE (CRM-STYLE)
    pub company_id: Option<String>,
    pub company_name: String,
    pub company_legal_name: Option<String>,
    pub company_aliases: Option<String>,
    pub company_size_range: Option<String>,
    pub company_revenue_range: Option<String>,
    pub company_industry: Option<String>,
    pub company_subindustry: Option<String>,
    pub company_stage: Option<String>, // startup, scaleup, enterprise
    pub company_founded_year: Option<i32>,
    pub company_headquarters_location: Option<String>,
    pub company_operating_countries: Option<String>,
    pub company_website: Option<String>,
    pub company_careers_page: Option<String>,
    pub company_glassdoor_url: Option<String>,
    pub company_linkedin_url: Option<String>,
    pub company_angellist_url: Option<String>,
    pub company_crunchbase_url: Option<String>,
    pub company_notes: Option<String>,
    pub company_rating: Option<f64>,
    pub company_culture_score: Option<f64>,
    pub company_work_life_balance: Option<f64>,
    pub company_diversity_score: Option<f64>,
    pub company_layoff_history_flag: bool,
    pub company_hiring_freeze_flag: bool,

    // 3. JOB POSTING DETAILS
    pub job_posting_url: Option<String>,
    pub job_posting_source: Option<String>,
    pub job_posting_platform: Option<String>,
    pub job_posting_id_external: Option<String>,
    pub job_posted_date: Option<String>,
    pub job_expiry_date: Option<String>,
    pub job_description_raw: Option<String>,
    pub job_description_clean: Option<String>,
    pub job_responsibilities: Option<String>,
    pub job_requirements: Option<String>,
    pub job_preferred_qualifications: Option<String>,
    pub job_keywords: Option<String>,
    pub job_seniority_keywords: Option<String>,
    pub job_location_text: Option<String>,
    pub job_location_country: Option<String>,
    pub job_location_state: Option<String>,
    pub job_location_city: Option<String>,
    pub job_location_lat: Option<f64>,
    pub job_location_lng: Option<f64>,
    pub relocation_required: bool,
    pub visa_sponsorship_available: bool,

    // 4. COMPENSATION & BENEFITS
    pub salary_currency: Option<String>,
    pub salary_min: Option<f64>,
    pub salary_max: Option<f64>,
    pub salary_midpoint: Option<f64>,
    pub salary_type: Option<String>, // annual, hourly
    pub salary_confidence_level: Option<f64>,
    pub equity_offered: bool,
    pub equity_type: Option<String>,
    pub equity_percentage: Option<f64>,
    pub equity_vesting_years: Option<i32>,
    pub bonus_available: bool,
    pub bonus_structure: Option<String>,
    pub bonus_target: Option<f64>,
    pub benefits_health: bool,
    pub benefits_retirement: bool,
    pub benefits_paid_leave: bool,
    pub benefits_learning_budget: bool,
    pub benefits_other: Option<String>,
    pub total_compensation_estimate: Option<f64>,
    pub compensation_notes: Option<String>,

    // 5. APPLICATION LIFECYCLE & TRACKING
    pub application_created_date: String,
    pub application_submitted_date: Option<String>,
    pub application_status: Option<String>,
    pub application_stage: Option<String>,
    pub application_stage_entered_at: Option<i64>,
    pub application_source: Option<String>,
    pub application_method: Option<String>,
    pub application_tracking_id: Option<String>,
    pub application_confirmation_flag: bool,
    pub application_confirmation_date: Option<String>,
    pub application_withdrawal_date: Option<String>,
    pub withdrawal_reason: Option<String>,
    pub ghosted_flag: bool,
    pub ghosted_detected_at: Option<i64>,

    // 6. RESUME, DOCUMENTS & MATERIALS
    pub resume_id: Option<String>,
    pub resume_filename: Option<String>,
    pub resume_version: Option<String>,
    pub resume_customized_for_job: bool,
    pub resume_keywords_targeted: Option<String>,
    pub resume_strength_score: Option<f64>,
    pub cover_letter_id: Option<String>,
    pub cover_letter_filename: Option<String>,
    pub cover_letter_customized: bool,
    pub portfolio_url: Option<String>,
    pub github_url: Option<String>,
    pub personal_website_url: Option<String>,
    pub additional_document_ids: Option<String>,
    pub document_submission_status: Option<String>,

    // 7. CONTACTS, RECRUITERS & REFERRALS
    pub recruiter_id: Option<String>,
    pub recruiter_name: Option<String>,
    pub recruiter_role: Option<String>,
    pub recruiter_email: Option<String>,
    pub recruiter_phone: Option<String>,
    pub recruiter_linkedin: Option<String>,
    pub hiring_manager_name: Option<String>,
    pub hiring_manager_role: Option<String>,
    pub hiring_manager_email: Option<String>,
    pub referral_contact_id: Option<String>,
    pub referral_name: Option<String>,
    pub referral_relationship: Option<String>,
    pub referral_strength_score: Option<f64>,
    pub contact_notes: Option<String>,

    // 8. INTERVIEW PROCESS & ASSESSMENTS
    pub interview_round_count: i32,
    pub interview_rounds_completed: i32,
    pub interview_current_round: Option<i32>,
    pub interview_format: Option<String>, // phone, video, onsite
    pub interview_dates: Option<String>,
    pub interview_timezones: Option<String>,
    pub interviewers: Option<String>,
    pub interview_feedback_scores: Option<String>,
    pub interview_feedback_notes: Option<String>,
    pub technical_test_required: bool,
    pub technical_test_type: Option<String>,
    pub technical_test_due_date: Option<String>,
    pub technical_test_score: Option<f64>,
    pub assignment_required: bool,
    pub assignment_score: Option<f64>,
    pub interview_outcome: Option<String>,

    // 9. OFFER, NEGOTIATION & DECISION
    pub offer_received_flag: bool,
    pub offer_date: Option<String>,
    pub offer_expiry_date: Option<String>,
    pub offer_salary: Option<f64>,
    pub offer_equity: Option<f64>,
    pub offer_bonus: Option<f64>,
    pub offer_benefits: Option<String>,
    pub offer_location: Option<String>,
    pub offer_remote_terms: Option<String>,
    pub offer_contract_type: Option<String>,
    pub offer_decision: Option<String>,
    pub offer_decision_date: Option<String>,
    pub negotiation_attempted: bool,
    pub negotiation_notes: Option<String>,
    pub counter_offer_details: Option<String>,

    // 10. REJECTION, OUTCOME & REAPPLICATION
    pub rejection_received_flag: bool,
    pub rejection_date: Option<String>,
    pub rejection_stage: Option<String>,
    pub rejection_reason: Option<String>,
    pub rejection_feedback: Option<String>,
    pub rejection_sentiment_score: Option<f64>,
    pub cooling_off_period_days: Option<i32>,
    pub reapply_eligible: bool,
    pub reapply_date: Option<String>,

    // 11. FOLLOW-UPS, REMINDERS & TASKS
    pub followup_required: bool,
    pub followup_count: i32,
    pub followup_last_sent_at: Option<i64>,
    pub followup_next_scheduled_at: Option<i64>,
    pub followup_template_id: Option<String>,
    pub thank_you_sent: bool,
    pub thank_you_sent_at: Option<i64>,
    pub reminder_enabled: bool,
    pub reminder_schedule: Option<String>,
    pub reminder_last_triggered_at: Option<i64>,

    // 12. TIME, ENERGY & EMOTIONAL LOAD
    pub time_spent_research_minutes: i32,
    pub time_spent_resume_minutes: i32,
    pub time_spent_interviews_minutes: i32,
    pub time_spent_followups_minutes: i32,
    pub total_time_spent_minutes: i32,
    pub cognitive_load_score: f64,
    pub emotional_load_score: f64,
    pub burnout_contribution_score: f64,

    // 13. ANALYTICS & PIPELINE HEALTH (DERIVED — READ ONLY)
    pub days_since_applied: Option<i32>,
    pub days_to_first_response: Option<i32>,
    pub response_received_flag: bool,
    pub interview_conversion_rate: f64,
    pub offer_conversion_rate: f64,
    pub rejection_rate: f64,
    pub ghost_rate: f64,
    pub avg_response_time: f64,
    pub pipeline_velocity: f64,
    pub application_success_probability: f64,
    pub job_pipeline_health_status: Option<String>,

    // 14. GOAL, HABIT & DIARY INTEGRATION
    pub linked_goal_ids: Option<String>,
    pub linked_habit_ids: Option<String>,
    pub job_related_habits_completed: i32,
    pub linked_diary_entry_ids: Option<String>,
    pub reflection_required: bool,
    pub reflection_completed: bool,
    pub job_search_phase: Option<String>,

    // 15. TAGGING, CLASSIFICATION & BATCHING
    pub tag_ids: Option<String>,
    pub tag_names_cache: Option<String>,
    pub priority_bucket: Option<String>,
    pub risk_bucket: Option<String>,
    pub opportunity_score: f64,
    pub confidence_bucket: Option<String>,
    pub job_search_batch_id: Option<String>,

    // 16. UI, DISPLAY & KANBAN CONTROL
    pub display_order: i32,
    pub display_column: Option<String>,
    pub display_hidden: bool,
    pub display_highlight: bool,
    pub display_badge: Option<String>,
    pub display_color_override: Option<String>,
    pub display_group: Option<String>,

    // 17. NOTIFICATIONS & ESCALATION
    pub notification_enabled: bool,
    pub notification_channels: Option<String>,
    pub notification_message: Option<String>,
    pub escalation_enabled: bool,
    pub escalation_delay: Option<i32>,
    pub escalation_last_triggered_at: Option<i64>,

    // 18. AUDIT, SECURITY & SYSTEM
    pub created_at: i64,
    pub updated_at: i64,
    pub last_viewed_at: Option<i64>,
    pub created_by_profile_id: Option<String>,
    pub last_modified_by_profile_id: Option<String>,
    pub device_id: Option<String>,
    pub session_id: Option<String>,
    pub app_version_created: Option<String>,
    pub app_version_last_modified: Option<String>,
    pub encryption_key_id: Option<String>,
    pub content_hash: Option<String>,
    pub sync_state: String,
    pub conflict_state: Option<String>,
    pub conflict_resolved_at: Option<i64>,
    pub data_migration_version: i32,

    // 19. SYSTEM & DEBUG (HIDDEN)
    pub is_system_generated: bool,
    pub is_template: bool,
    pub template_source: Option<String>,
    pub internal_flags: Option<String>,
    pub experimental_fields: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateJobInput {
    pub job_title: String,
    pub company_name: String,
    pub job_level: Option<String>,
    pub job_employment_type: Option<String>,
    pub job_work_mode: Option<String>,
    pub job_posting_url: Option<String>,
}
