-- 0002_diary.sql
CREATE TABLE diary_entries (
    diary_entry_id TEXT PRIMARY KEY NOT NULL,
    entry_date TEXT NOT NULL,
    entry_year INTEGER NOT NULL,
    entry_month INTEGER NOT NULL,
    entry_day INTEGER NOT NULL,
    entry_week_of_year INTEGER NOT NULL,
    entry_day_of_week INTEGER NOT NULL,
    is_primary_page INTEGER NOT NULL DEFAULT 0,
    primary_page_id TEXT,
    is_auto_created INTEGER NOT NULL DEFAULT 0,
    auto_creation_reason TEXT,
    calendar_type TEXT NOT NULL DEFAULT 'gregorian',
    timezone_at_creation TEXT,
    date_locked INTEGER NOT NULL DEFAULT 0,
    date_last_validated_at INTEGER,
    parent_page_id TEXT,
    root_page_id TEXT,
    page_depth INTEGER NOT NULL DEFAULT 0,
    page_path TEXT,
    page_sort_index INTEGER NOT NULL DEFAULT 0,
    page_position_type TEXT NOT NULL DEFAULT 'middle',
    has_children INTEGER NOT NULL DEFAULT 0,
    children_count INTEGER NOT NULL DEFAULT 0,
    descendant_count INTEGER NOT NULL DEFAULT 0,
    is_collapsed_by_default INTEGER NOT NULL DEFAULT 0,
    is_archived INTEGER NOT NULL DEFAULT 0,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    deleted_at INTEGER,
    deleted_reason TEXT,
    restore_parent_id TEXT,
    tree_version INTEGER NOT NULL DEFAULT 1,
    title TEXT,
    title_plaintext TEXT,
    content_json TEXT NOT NULL,
    content_plaintext TEXT,
    content_html_cache TEXT,
    block_count INTEGER NOT NULL DEFAULT 0,
    paragraph_count INTEGER NOT NULL DEFAULT 0,
    heading_count INTEGER NOT NULL DEFAULT 0,
    list_count INTEGER NOT NULL DEFAULT 0,
    code_block_count INTEGER NOT NULL DEFAULT 0,
    table_count INTEGER NOT NULL DEFAULT 0,
    toggle_count INTEGER NOT NULL DEFAULT 0,
    embed_count INTEGER NOT NULL DEFAULT 0,
    inline_comment_count INTEGER NOT NULL DEFAULT 0,
    content_schema_version INTEGER NOT NULL DEFAULT 1,
    last_block_edit_at INTEGER,
    word_count INTEGER NOT NULL DEFAULT 0,
    character_count INTEGER NOT NULL DEFAULT 0,
    sentence_count INTEGER NOT NULL DEFAULT 0,
    reading_time_minutes INTEGER NOT NULL DEFAULT 0,
    writing_time_seconds INTEGER NOT NULL DEFAULT 0,
    revision_count INTEGER NOT NULL DEFAULT 0,
    avg_words_per_paragraph REAL NOT NULL DEFAULT 0.0,
    is_empty_entry INTEGER NOT NULL DEFAULT 1,
    length_category TEXT,
    length_score REAL NOT NULL DEFAULT 0.0,
    last_length_change_at INTEGER,
    tag_ids TEXT,
    tag_names_cache TEXT,
    tag_count INTEGER NOT NULL DEFAULT 0,
    primary_category TEXT,
    secondary_categories TEXT,
    semantic_type TEXT,
    custom_labels TEXT,
    color_label TEXT,
    icon_emoji TEXT,
    importance_level INTEGER NOT NULL DEFAULT 0,
    confidence_level INTEGER NOT NULL DEFAULT 0,
    intent_type TEXT,
    mood_rating INTEGER,
    mood_label TEXT,
    energy_level INTEGER,
    stress_level INTEGER,
    sleep_quality INTEGER,
    weather_type TEXT,
    weather_temperature REAL,
    location_text TEXT,
    location_lat REAL,
    location_lng REAL,
    social_context TEXT,
    health_context_notes TEXT,
    gratitude_items TEXT,
    linked_habit_ids TEXT,
    completed_habit_ids TEXT,
    linked_goal_ids TEXT,
    progressed_goal_ids TEXT,
    linked_task_ids TEXT,
    linked_job_ids TEXT,
    linked_attachment_ids TEXT,
    backlink_page_ids TEXT,
    forward_link_page_ids TEXT,
    relation_strength_score REAL NOT NULL DEFAULT 0.0,
    is_counted_for_streak INTEGER NOT NULL DEFAULT 0,
    daily_streak_index INTEGER,
    is_streak_breaker INTEGER NOT NULL DEFAULT 0,
    yearly_day_index INTEGER,
    is_filled_day INTEGER NOT NULL DEFAULT 0,
    filled_day_score REAL NOT NULL DEFAULT 0.0,
    year_completion_percentage REAL NOT NULL DEFAULT 0.0,
    rolling_7_day_avg_words REAL NOT NULL DEFAULT 0.0,
    rolling_30_day_avg_words REAL NOT NULL DEFAULT 0.0,
    longest_streak_so_far INTEGER NOT NULL DEFAULT 0,
    current_streak_length INTEGER NOT NULL DEFAULT 0,
    streak_last_updated_at INTEGER,
    filter_date_bucket TEXT,
    filter_has_children INTEGER NOT NULL DEFAULT 0,
    filter_has_tags INTEGER NOT NULL DEFAULT 0,
    filter_length_bucket TEXT,
    filter_mood_bucket TEXT,
    sort_title_normalized TEXT,
    sort_date_numeric INTEGER,
    sort_last_edited_numeric INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_viewed_at INTEGER,
    created_by_profile_id TEXT,
    last_modified_by_profile_id TEXT,
    device_id TEXT,
    session_id TEXT,
    app_version_created TEXT,
    app_version_last_modified TEXT,
    content_hash TEXT,
    encryption_key_id TEXT,
    sync_state TEXT DEFAULT 'local',
    conflict_state TEXT,
    conflict_resolved_at INTEGER,
    data_migration_version INTEGER NOT NULL DEFAULT 1,
    is_system_generated INTEGER NOT NULL DEFAULT 0,
    is_recovered_entry INTEGER NOT NULL DEFAULT 0,
    recovery_source TEXT,
    debug_notes TEXT,
    internal_flags TEXT,
    experimental_fields TEXT,
    FOREIGN KEY (primary_page_id) REFERENCES diary_entries(diary_entry_id),
    FOREIGN KEY (parent_page_id) REFERENCES diary_entries(diary_entry_id),
    FOREIGN KEY (root_page_id) REFERENCES diary_entries(diary_entry_id)
);
