-- 0003_habits.sql

CREATE TABLE habits (
    -- 1. CORE IDENTITY
    habit_id TEXT PRIMARY KEY NOT NULL,
    habit_slug TEXT,
    habit_name TEXT NOT NULL,
    habit_description TEXT,
    habit_short_description TEXT,
    habit_type TEXT NOT NULL, -- boolean, quantitative, duration, checklist
    habit_category TEXT,
    habit_subcategory TEXT,
    habit_domain TEXT,
    habit_icon_emoji TEXT,
    habit_color TEXT,
    habit_visibility TEXT NOT NULL DEFAULT 'active', -- active, paused, archived
    habit_priority_level INTEGER NOT NULL DEFAULT 0,
    habit_difficulty_level INTEGER NOT NULL DEFAULT 0,
    habit_motivation_score REAL NOT NULL DEFAULT 0.0,
    habit_identity_statement TEXT,
    habit_version INTEGER NOT NULL DEFAULT 1,

    -- 2. SCHEDULING & FREQUENCY
    schedule_type TEXT NOT NULL DEFAULT 'daily', -- daily, weekly, custom, interval
    schedule_days_of_week TEXT,
    schedule_days_of_month TEXT,
    schedule_weeks_of_year TEXT,
    schedule_interval_value INTEGER,
    schedule_interval_unit TEXT,
    schedule_start_date TEXT,
    schedule_end_date TEXT,
    schedule_timezone TEXT,
    schedule_is_flexible INTEGER NOT NULL DEFAULT 0,
    schedule_grace_period_minutes INTEGER NOT NULL DEFAULT 0,
    schedule_cutoff_time TEXT,
    schedule_requires_exact_time INTEGER NOT NULL DEFAULT 0,
    schedule_time_windows TEXT,
    schedule_excluded_dates TEXT,
    schedule_holiday_behavior TEXT,
    schedule_weekend_behavior TEXT,
    schedule_failure_reset_rule TEXT,

    -- 3. TARGET & MEASUREMENT
    target_type TEXT NOT NULL DEFAULT 'boolean', -- count, duration, amount
    target_value REAL,
    target_unit TEXT,
    target_operator TEXT NOT NULL DEFAULT '>=', -- >=, ==, <=
    min_target_value REAL,
    max_target_value REAL,
    ideal_target_value REAL,
    baseline_value REAL,
    rolling_target_window INTEGER,
    carryover_behavior TEXT,
    overflow_behavior TEXT,
    partial_completion_allowed INTEGER NOT NULL DEFAULT 0,
    partial_completion_weight REAL NOT NULL DEFAULT 0.0,
    completion_threshold_percent REAL NOT NULL DEFAULT 0.0,
    overachievement_allowed INTEGER NOT NULL DEFAULT 0,
    overachievement_cap REAL,
    diminishing_returns_curve TEXT,

    -- 4. DAILY CHECK-IN
    checkin_required INTEGER NOT NULL DEFAULT 1,
    checkin_mode TEXT NOT NULL DEFAULT 'manual', -- manual, auto, mixed
    checkin_input_type TEXT,
    checkin_default_value REAL,
    checkin_last_value REAL,
    checkin_notes TEXT,
    checkin_media_allowed INTEGER NOT NULL DEFAULT 0,
    checkin_voice_allowed INTEGER NOT NULL DEFAULT 0,
    checkin_photo_allowed INTEGER NOT NULL DEFAULT 0,
    checkin_location_required INTEGER NOT NULL DEFAULT 0,
    checkin_weather_required INTEGER NOT NULL DEFAULT 0,
    checkin_mood_required INTEGER NOT NULL DEFAULT 0,
    checkin_energy_required INTEGER NOT NULL DEFAULT 0,
    checkin_prompt_text TEXT,
    checkin_confirmation_required INTEGER NOT NULL DEFAULT 0,
    checkin_failure_reason TEXT,
    checkin_retry_allowed INTEGER NOT NULL DEFAULT 0,
    checkin_retry_limit INTEGER NOT NULL DEFAULT 0,

    -- 5. STREAK LOGIC
    streak_current INTEGER NOT NULL DEFAULT 0,
    streak_longest INTEGER NOT NULL DEFAULT 0,
    streak_best_window INTEGER NOT NULL DEFAULT 0,
    streak_start_date TEXT,
    streak_last_updated_at INTEGER,
    streak_freeze_available INTEGER NOT NULL DEFAULT 0,
    streak_freeze_used INTEGER NOT NULL DEFAULT 0,
    streak_freeze_remaining INTEGER NOT NULL DEFAULT 0,
    streak_break_reason TEXT,
    streak_break_date TEXT,
    streak_repair_allowed INTEGER NOT NULL DEFAULT 0,
    streak_repair_used INTEGER NOT NULL DEFAULT 0,
    streak_decay_model TEXT,
    streak_weight REAL NOT NULL DEFAULT 1.0,

    -- 6. PERFORMANCE METRICS (DERIVED)
    total_completions INTEGER NOT NULL DEFAULT 0,
    total_failures INTEGER NOT NULL DEFAULT 0,
    total_skips INTEGER NOT NULL DEFAULT 0,
    completion_rate_lifetime REAL NOT NULL DEFAULT 0.0,
    completion_rate_30d REAL NOT NULL DEFAULT 0.0,
    completion_rate_90d REAL NOT NULL DEFAULT 0.0,
    completion_rate_365d REAL NOT NULL DEFAULT 0.0,
    consistency_index REAL NOT NULL DEFAULT 0.0,
    variance_score REAL NOT NULL DEFAULT 0.0,
    momentum_score REAL NOT NULL DEFAULT 0.0,
    habit_strength_score REAL NOT NULL DEFAULT 0.0,
    habit_entropy_score REAL NOT NULL DEFAULT 0.0,
    habit_predictability_score REAL NOT NULL DEFAULT 0.0,

    -- 7. REWARDS & GAMIFICATION
    reward_type TEXT,
    reward_value REAL,
    reward_currency TEXT,
    reward_frequency TEXT,
    reward_cap REAL,
    punishment_type TEXT,
    punishment_value REAL,
    punishment_trigger TEXT,
    loss_aversion_enabled INTEGER NOT NULL DEFAULT 0,
    gamification_points INTEGER NOT NULL DEFAULT 0,
    gamification_level INTEGER NOT NULL DEFAULT 1,
    gamification_xp INTEGER NOT NULL DEFAULT 0,
    gamification_badges TEXT,

    -- 8. MOTIVATION & PSYCHOLOGY
    motivation_type TEXT, -- intrinsic, extrinsic
    motivation_reason TEXT,
    motivation_quote TEXT,
    identity_alignment_score REAL NOT NULL DEFAULT 0.0,
    emotional_resistance_score REAL NOT NULL DEFAULT 0.0,
    friction_level REAL NOT NULL DEFAULT 0.0,
    activation_energy_score REAL NOT NULL DEFAULT 0.0,
    habit_loop_cue TEXT,
    habit_loop_routine TEXT,
    habit_loop_reward TEXT,
    temptation_bundling_enabled INTEGER NOT NULL DEFAULT 0,

    -- 9. DEPENDENCIES & RELATIONS
    prerequisite_habit_ids TEXT,
    dependent_habit_ids TEXT,
    blocked_by_habit_ids TEXT,
    unlocks_habit_ids TEXT,
    linked_goal_ids TEXT,
    contributing_goal_weight REAL NOT NULL DEFAULT 0.0,
    linked_task_ids TEXT,
    linked_diary_page_ids TEXT,
    linked_job_ids TEXT,
    dependency_strength_score REAL NOT NULL DEFAULT 0.0,

    -- 10. ANALYTICS (READ-ONLY)
    is_on_track INTEGER NOT NULL DEFAULT 1,
    projected_completion_rate REAL NOT NULL DEFAULT 0.0,
    projected_streak_length INTEGER NOT NULL DEFAULT 0,
    habit_health_status TEXT,
    burnout_risk_score REAL NOT NULL DEFAULT 0.0,
    relapse_risk_score REAL NOT NULL DEFAULT 0.0,
    success_probability REAL NOT NULL DEFAULT 0.0,

    -- 11. AUDIT & SYSTEM
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_completed_at INTEGER,
    last_failed_at INTEGER,
    last_skipped_at INTEGER,
    created_by_profile_id TEXT,
    last_modified_by_profile_id TEXT,
    device_id TEXT,
    session_id TEXT,
    app_version_created TEXT,
    app_version_last_modified TEXT,
    encryption_key_id TEXT,
    content_hash TEXT,
    sync_state TEXT NOT NULL DEFAULT 'local',
    conflict_state TEXT,
    conflict_resolved_at INTEGER,
    internal_flags TEXT,
    experimental_fields TEXT
);
