-- 0005_jobs.sql

CREATE TABLE job_applications (
    -- 1. CORE IDENTITY & PIPELINE STATUS
    job_application_id TEXT PRIMARY KEY NOT NULL,
    job_application_slug TEXT UNIQUE NOT NULL,
    job_title TEXT NOT NULL,
    job_title_normalized TEXT,
    job_level TEXT, -- junior, mid, senior, staff, lead
    job_employment_type TEXT, -- full_time, part_time, contract, internship
    job_work_mode TEXT, -- onsite, hybrid, remote
    job_department TEXT,
    job_function TEXT,
    job_industry TEXT,
    job_domain TEXT,
    job_priority_level INTEGER NOT NULL DEFAULT 0,
    job_interest_level INTEGER NOT NULL DEFAULT 0,
    job_fit_score REAL NOT NULL DEFAULT 0.0,
    job_visibility TEXT NOT NULL DEFAULT 'active', -- active, archived
    job_status TEXT NOT NULL DEFAULT 'draft', -- draft, applied, interviewing, offer, rejected, ghosted, withdrawn
    job_stage TEXT,
    job_stage_order INTEGER NOT NULL DEFAULT 0,
    job_version INTEGER NOT NULL DEFAULT 1,

    -- 2. COMPANY PROFILE (CRM-STYLE)
    company_id TEXT,
    company_name TEXT NOT NULL,
    company_legal_name TEXT,
    company_aliases TEXT,
    company_size_range TEXT,
    company_revenue_range TEXT,
    company_industry TEXT,
    company_subindustry TEXT,
    company_stage TEXT, -- startup, scaleup, enterprise
    company_founded_year INTEGER,
    company_headquarters_location TEXT,
    company_operating_countries TEXT,
    company_website TEXT,
    company_careers_page TEXT,
    company_glassdoor_url TEXT,
    company_linkedin_url TEXT,
    company_angellist_url TEXT,
    company_crunchbase_url TEXT,
    company_notes TEXT,
    company_rating REAL,
    company_culture_score REAL,
    company_work_life_balance REAL,
    company_diversity_score REAL,
    company_layoff_history_flag INTEGER NOT NULL DEFAULT 0,
    company_hiring_freeze_flag INTEGER NOT NULL DEFAULT 0,

    -- 3. JOB POSTING DETAILS
    job_posting_url TEXT,
    job_posting_source TEXT,
    job_posting_platform TEXT,
    job_posting_id_external TEXT,
    job_posted_date TEXT,
    job_expiry_date TEXT,
    job_description_raw TEXT,
    job_description_clean TEXT,
    job_responsibilities TEXT,
    job_requirements TEXT,
    job_preferred_qualifications TEXT,
    job_keywords TEXT,
    job_seniority_keywords TEXT,
    job_location_text TEXT,
    job_location_country TEXT,
    job_location_state TEXT,
    job_location_city TEXT,
    job_location_lat REAL,
    job_location_lng REAL,
    relocation_required INTEGER NOT NULL DEFAULT 0,
    visa_sponsorship_available INTEGER NOT NULL DEFAULT 0,

    -- 4. COMPENSATION & BENEFITS
    salary_currency TEXT,
    salary_min REAL,
    salary_max REAL,
    salary_midpoint REAL,
    salary_type TEXT, -- annual, hourly
    salary_confidence_level REAL,
    equity_offered INTEGER NOT NULL DEFAULT 0,
    equity_type TEXT,
    equity_percentage REAL,
    equity_vesting_years INTEGER,
    bonus_available INTEGER NOT NULL DEFAULT 0,
    bonus_structure TEXT,
    bonus_target REAL,
    benefits_health INTEGER NOT NULL DEFAULT 0,
    benefits_retirement INTEGER NOT NULL DEFAULT 0,
    benefits_paid_leave INTEGER NOT NULL DEFAULT 0,
    benefits_learning_budget INTEGER NOT NULL DEFAULT 0,
    benefits_other TEXT,
    total_compensation_estimate REAL,
    compensation_notes TEXT,

    -- 5. APPLICATION LIFECYCLE & TRACKING
    application_created_date TEXT NOT NULL,
    application_submitted_date TEXT,
    application_status TEXT,
    application_stage TEXT,
    application_stage_entered_at INTEGER,
    application_source TEXT,
    application_method TEXT,
    application_tracking_id TEXT,
    application_confirmation_flag INTEGER NOT NULL DEFAULT 0,
    application_confirmation_date TEXT,
    application_withdrawal_date TEXT,
    withdrawal_reason TEXT,
    ghosted_flag INTEGER NOT NULL DEFAULT 0,
    ghosted_detected_at INTEGER,

    -- 6. RESUME, DOCUMENTS & MATERIALS
    resume_id TEXT,
    resume_filename TEXT,
    resume_version TEXT,
    resume_customized_for_job INTEGER NOT NULL DEFAULT 0,
    resume_keywords_targeted TEXT,
    resume_strength_score REAL,
    cover_letter_id TEXT,
    cover_letter_filename TEXT,
    cover_letter_customized INTEGER NOT NULL DEFAULT 0,
    portfolio_url TEXT,
    github_url TEXT,
    personal_website_url TEXT,
    additional_document_ids TEXT,
    document_submission_status TEXT,

    -- 7. CONTACTS, RECRUITERS & REFERRALS
    recruiter_id TEXT,
    recruiter_name TEXT,
    recruiter_role TEXT,
    recruiter_email TEXT,
    recruiter_phone TEXT,
    recruiter_linkedin TEXT,
    hiring_manager_name TEXT,
    hiring_manager_role TEXT,
    hiring_manager_email TEXT,
    referral_contact_id TEXT,
    referral_name TEXT,
    referral_relationship TEXT,
    referral_strength_score REAL,
    contact_notes TEXT,

    -- 8. INTERVIEW PROCESS & ASSESSMENTS
    interview_round_count INTEGER NOT NULL DEFAULT 0,
    interview_rounds_completed INTEGER NOT NULL DEFAULT 0,
    interview_current_round INTEGER,
    interview_format TEXT, -- phone, video, onsite
    interview_dates TEXT,
    interview_timezones TEXT,
    interviewers TEXT,
    interview_feedback_scores TEXT,
    interview_feedback_notes TEXT,
    technical_test_required INTEGER NOT NULL DEFAULT 0,
    technical_test_type TEXT,
    technical_test_due_date TEXT,
    technical_test_score REAL,
    assignment_required INTEGER NOT NULL DEFAULT 0,
    assignment_score REAL,
    interview_outcome TEXT,

    -- 9. OFFER, NEGOTIATION & DECISION
    offer_received_flag INTEGER NOT NULL DEFAULT 0,
    offer_date TEXT,
    offer_expiry_date TEXT,
    offer_salary REAL,
    offer_equity REAL,
    offer_bonus REAL,
    offer_benefits TEXT,
    offer_location TEXT,
    offer_remote_terms TEXT,
    offer_contract_type TEXT,
    offer_decision TEXT,
    offer_decision_date TEXT,
    negotiation_attempted INTEGER NOT NULL DEFAULT 0,
    negotiation_notes TEXT,
    counter_offer_details TEXT,

    -- 10. REJECTION, OUTCOME & REAPPLICATION
    rejection_received_flag INTEGER NOT NULL DEFAULT 0,
    rejection_date TEXT,
    rejection_stage TEXT,
    rejection_reason TEXT,
    rejection_feedback TEXT,
    rejection_sentiment_score REAL,
    cooling_off_period_days INTEGER,
    reapply_eligible INTEGER NOT NULL DEFAULT 1,
    reapply_date TEXT,

    -- 11. FOLLOW-UPS, REMINDERS & TASKS
    followup_required INTEGER NOT NULL DEFAULT 0,
    followup_count INTEGER NOT NULL DEFAULT 0,
    followup_last_sent_at INTEGER,
    followup_next_scheduled_at INTEGER,
    followup_template_id TEXT,
    thank_you_sent INTEGER NOT NULL DEFAULT 0,
    thank_you_sent_at INTEGER,
    reminder_enabled INTEGER NOT NULL DEFAULT 0,
    reminder_schedule TEXT,
    reminder_last_triggered_at INTEGER,

    -- 12. TIME, ENERGY & EMOTIONAL LOAD
    time_spent_research_minutes INTEGER NOT NULL DEFAULT 0,
    time_spent_resume_minutes INTEGER NOT NULL DEFAULT 0,
    time_spent_interviews_minutes INTEGER NOT NULL DEFAULT 0,
    time_spent_followups_minutes INTEGER NOT NULL DEFAULT 0,
    total_time_spent_minutes INTEGER NOT NULL DEFAULT 0,
    cognitive_load_score REAL NOT NULL DEFAULT 0.0,
    emotional_load_score REAL NOT NULL DEFAULT 0.0,
    burnout_contribution_score REAL NOT NULL DEFAULT 0.0,

    -- 13. ANALYTICS & PIPELINE HEALTH (DERIVED — READ ONLY)
    days_since_applied INTEGER,
    days_to_first_response INTEGER,
    response_received_flag INTEGER NOT NULL DEFAULT 0,
    interview_conversion_rate REAL NOT NULL DEFAULT 0.0,
    offer_conversion_rate REAL NOT NULL DEFAULT 0.0,
    rejection_rate REAL NOT NULL DEFAULT 0.0,
    ghost_rate REAL NOT NULL DEFAULT 0.0,
    avg_response_time REAL NOT NULL DEFAULT 0.0,
    pipeline_velocity REAL NOT NULL DEFAULT 0.0,
    application_success_probability REAL NOT NULL DEFAULT 0.0,
    job_pipeline_health_status TEXT,

    -- 14. GOAL, HABIT & DIARY INTEGRATION
    linked_goal_ids TEXT,
    linked_habit_ids TEXT,
    job_related_habits_completed INTEGER NOT NULL DEFAULT 0,
    linked_diary_entry_ids TEXT,
    reflection_required INTEGER NOT NULL DEFAULT 0,
    reflection_completed INTEGER NOT NULL DEFAULT 0,
    job_search_phase TEXT,

    -- 15. TAGGING, CLASSIFICATION & BATCHING
    tag_ids TEXT,
    tag_names_cache TEXT,
    priority_bucket TEXT,
    risk_bucket TEXT,
    opportunity_score REAL NOT NULL DEFAULT 0.0,
    confidence_bucket TEXT,
    job_search_batch_id TEXT,

    -- 16. UI, DISPLAY & KANBAN CONTROL
    display_order INTEGER NOT NULL DEFAULT 0,
    display_column TEXT,
    display_hidden INTEGER NOT NULL DEFAULT 0,
    display_highlight INTEGER NOT NULL DEFAULT 0,
    display_badge TEXT,
    display_color_override TEXT,
    display_group TEXT,

    -- 17. NOTIFICATIONS & ESCALATION
    notification_enabled INTEGER NOT NULL DEFAULT 1,
    notification_channels TEXT,
    notification_message TEXT,
    escalation_enabled INTEGER NOT NULL DEFAULT 0,
    escalation_delay INTEGER,
    escalation_last_triggered_at INTEGER,

    -- 18. AUDIT, SECURITY & SYSTEM
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_viewed_at INTEGER,
    created_by_profile_id TEXT,
    last_modified_by_profile_id TEXT,
    device_id TEXT,
    session_id TEXT,
    app_version_created TEXT,
    app_version_last_modified TEXT,
    encryption_key_id TEXT,
    content_hash TEXT,
    sync_state TEXT NOT NULL DEFAULT 'local',
    conflict_state TEXT,
    conflict_resolved_at INTEGER,
    data_migration_version INTEGER NOT NULL DEFAULT 1,

    -- 19. SYSTEM & DEBUG (HIDDEN)
    is_system_generated INTEGER NOT NULL DEFAULT 0,
    is_template INTEGER NOT NULL DEFAULT 0,
    template_source TEXT,
    internal_flags TEXT,
    experimental_fields TEXT
);
